/**
 * Local bridge from the game taxonomy to OpenAlex's live Topics taxonomy.
 * The API resolves these curated labels to Topic IDs before querying Works,
 * so retrieval is constrained by OpenAlex classification rather than title
 * keyword matching.
 */
export const openAlexMappings: Record<string, string[]> = {
  ecology: ["ecology", "community ecology", "ecosystem ecology"],
  "evolutionary-biology": ["evolutionary biology", "molecular evolution"],
  "biodiversity-conservation": ["biodiversity conservation", "conservation biology"],
  "marine-and-freshwater-biology": ["marine biology", "freshwater ecology"],
  limnology: ["limnology", "freshwater ecology"],
  fisheries: ["fisheries", "fish ecology"],
  "environmental-sciences": ["environmental science", "environmental pollution"],
  "environmental-studies": ["environmental studies", "sustainability"],
  "plant-sciences": ["plant science", "plant physiology"],
  zoology: ["zoology", "animal ecology"],
  entomology: ["entomology", "insect ecology"],
  ornithology: ["ornithology", "bird ecology"],
  microbiology: ["microbiology", "microbial ecology"],
  "biotechnology-and-applied-microbiology": ["biotechnology", "applied microbiology"],
  "genetics-and-heredity": ["genetics", "heredity"],
  "cell-biology": ["cell biology", "cell signaling"],
  "biochemistry-and-molecular-biology": ["biochemistry", "molecular biology"],
  neurosciences: ["neuroscience", "cognitive neuroscience"],
  physiology: ["physiology", "human physiology"],
  "developmental-biology": ["developmental biology", "embryology"],
  "medicine-general-and-internal": ["internal medicine", "general medicine"],
  "public-environmental-and-occupational-health": ["public health", "occupational health"],
  oncology: ["oncology", "cancer research"],
  immunology: ["immunology", "immune response"],
  "infectious-diseases": ["infectious disease", "epidemiology of infectious disease"],
  psychiatry: ["psychiatry", "mental health"],
  "clinical-neurology": ["clinical neurology", "neurological disorders"],
  "cardiac-and-cardiovascular-systems": ["cardiology", "cardiovascular disease"],
  "endocrinology-and-metabolism": ["endocrinology", "metabolic disease"],
  "pharmacology-and-pharmacy": ["pharmacology", "drug development"],
  "gastroenterology-and-hepatology": ["gastroenterology", "hepatology"],
  "respiratory-system": ["respiratory medicine", "pulmonary disease"],
  "physics-multidisciplinary": ["physics", "theoretical physics"],
  "applied-physics": ["applied physics", "experimental physics"],
  "astronomy-and-astrophysics": ["astronomy", "astrophysics"],
  "chemistry-multidisciplinary": ["chemistry", "chemical science"],
  "physical-chemistry": ["physical chemistry", "chemical thermodynamics"],
  "analytical-chemistry": ["analytical chemistry", "chemical analysis"],
  "organic-chemistry": ["organic chemistry", "organic synthesis"],
  "materials-science-multidisciplinary": ["materials science", "advanced materials"],
  "geosciences-multidisciplinary": ["geoscience", "earth science"],
  "meteorology-and-atmospheric-sciences": ["atmospheric science", "meteorology"],
  oceanography: ["oceanography", "physical oceanography"],
  "computer-science-artificial-intelligence": [
    "Machine Learning and Algorithms",
    "Artificial Intelligence Applications",
    "Artificial Intelligence in Games",
  ],
  "computer-science-information-systems": ["information systems", "database systems"],
  "computer-science-theory-and-methods": ["theoretical computer science", "algorithms"],
  "engineering-electrical-and-electronic": ["electrical engineering", "electronic engineering"],
  "engineering-environmental": ["environmental engineering", "water treatment"],
  "engineering-biomedical": ["biomedical engineering", "medical devices"],
  "mechanical-engineering": ["mechanical engineering", "mechanics"],
  "chemical-engineering": ["chemical engineering", "process engineering"],
  robotics: ["robotics", "autonomous robots"],
  "automation-and-control-systems": ["control systems", "automation"],
  economics: ["economics", "applied economics"],
  "psychology-multidisciplinary": ["psychology", "behavioral science"],
  "psychology-experimental": ["experimental psychology", "cognitive psychology"],
  "psychology-social": ["social psychology", "social cognition"],
  sociology: ["sociology", "social structure"],
  "political-science": ["political science", "comparative politics"],
  geography: ["human geography", "geography"],
  business: ["business", "business strategy"],
  management: ["management science", "organizational management"],
  "education-and-educational-research": ["education research", "learning sciences"],
  communication: ["communication studies", "media studies"],
  "international-relations": ["international relations", "international politics"],
};
